### ISSUE TITLE
Steam Deck Canary Update Problem

### ISSUE THREAD

**Issue by M45TR0** [dotaxis/7thDeck#39]
Every time I try to update to 3.9.9.28 on my Steam Deck, the batch file for the update starts and I get an error "Internal error: Failed to expand shell folder constant "userpf"".

Afterwards I tried to update to 3.5.1.0 and it worked without a problem, but now I'm unable to get back to the canary builds.

Same happening with 3.9.9.29 now. I put an Issue on 7th Heaven github first, but they told me to ask the question here, since they don't maintain the Steam Deck.

Steam OS: 3.5.19

**Comment by dotaxis** [comment]
Canary is not something I can support right now because of the drastic changes that are being made to how 7th Heaven works in canary.

I'm working on a rust rewrite which will support both stable and canary but may require different install paths, but I haven't had much time to work on it so it's moving slowly.

I'll leave this open until the rust rewrite is done and I can officially support canary, but don't hold your breath. It will be a while.

**Comment by dotaxis** [comment]
Sorry this took so long. We are ramping up testing for 7th Heaven 4.0 and my rust rewrite will not be ready in time.

I've opened a PR in the 7th Heaven repo which should solve this issue.

**Comment by M45TR0** [comment]
No worries. I can confirm that 3.9.9.45 solved that problem and I was able to install it without an issue. Thanks for your work.

Not sure if you want to have this keep open, so I just close the ticket.

**Comment by dotaxis** [comment]
Does 7th Heaven actually work with mods on canary after doing an upgrade?

**Comment by M45TR0** [comment]
Yes. I was able to launch the game with Mods. At first I had issues with "Please launch the game with "FF7_launcher.exe"." But it seems like my FFNx got deleted. After reinstalling it, it all worked fine.

But I realized, that the 7th Heaven screen freezes randomly, can't really pinpoint the issue there.

**Comment by dotaxis** [comment]
Interesting. Canary is very unstable on Linux at the moment and I would recommend not using it for the time being.

Personally I'm unable to get mods working in it at all.
